all: ../images/oriented-tree.svg ../images/oriented-forest.svg

../images/oriented-tree.svg: oriented-tree.asy
	asy oriented-tree.asy -f svg -o ../images/

../images/oriented-forest.svg: oriented-forest.asy
	asy oriented-forest.asy -f svg -o ../images/
