all: ../images/oriented-tree.png ../images/oriented-forest.png

../images/oriented-tree.png: oriented-tree.asy
	asy oriented-tree.asy -f png -o ../images/

../images/oriented-forest.png: oriented-forest.asy
	asy oriented-forest.asy -f png -o ../images/
